name: Deployando nuestras primeras actions de Github

on:
  push:
    branches: [main]

jobs:
  platzi: 
    runs-on: ubuntu-latest

    steps:
      - name: "Hello world"
        run: echo "Hola mundo desde Github actions"